### ISSUE TITLE
The order of the attributes changes randomly

### ISSUE THREAD

**Issue by acecilia** [MaxDesiatov/XMLCoder#108]
I noticed that when there are multiple attributes, every time I encode the model they are ordered in a different way in the resulting `xml`. This is a huge problem during unit tests, where it becomes impossible to validate the encoded `Data` (or `String`)  against a reference one.

Is this a known issue?

Thanks,
Andres

**Comment by MaxDesiatov** [comment]
Hi @acecilia, thank you for reporting this. I thought this was fixed in 0.6.0 with #102 being merged, but interesting to see this still being reproduced. Do you have any specific unit tests you'd be able to share? If so, would you mind if I add them to XMLCoder's test suite?

**Comment by acecilia** [comment]
Sure. Find in https://github.com/MaxDesiatov/XMLCoder/pull/109 some tests that showcase the problem and a small explanation of why this happens. Find in https://github.com/MaxDesiatov/XMLCoder/pull/110 a fix for it :)
