### ISSUE TITLE
Can’t reach an XML value

### ISSUE THREAD

**Issue by qmoya** [MaxDesiatov/XMLCoder#12]
Hi there! I can’t find the right data structure to decode the following XML string:

    <something name="Some name">Some value</something>

I ran out of ideas. May anyone give me a hint?

Thanks!

**Comment by MaxDesiatov** [comment]
This is now supported in `master` with #73 merged. As usual please feel free to reopen this issue if you think there's anything missing.

**Comment by thecb4** [comment]
Trying to use master with the following and still getting an error
 
<preview_image_time format="24/999 1000/nonDrop">00:00:17:01</preview_image_time>

------ 

struct PreviewImageTime: Codable, DynamicNodeEncoding {
  var format: String
  var value: String

  enum CodingKeys: String, CodingKey {
    case format
    case value = ""
  }

  static func nodeEncoding(forKey key: CodingKey) -> XMLEncoder.NodeEncoding {
    switch key {
      case CodingKeys.format:
        return .attribute
      default:
        return .element
    }
  }
}
------------------------

could not parse
typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "software", intValue: nil), CodingKeys(stringValue: "software_metadata", intValue: nil), CodingKeys(stringValue: "versions", intValue: nil), CodingKeys(stringValue: "version", intValue: nil), XMLKey(stringValue: "0", intValue: 0), CodingKeys(stringValue: "locales", intValue: nil), CodingKeys(stringValue: "locale", intValue: nil), XMLKey(stringValue: "0", intValue: 0), CodingKeys(stringValue: "app_previews", intValue: nil), CodingKeys(stringValue: "app_preview", intValue: nil), XMLKey(stringValue: "0", intValue: 0), CodingKeys(stringValue: "preview_image_time", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found SharedBox<UnkeyedBox> instead.", underlyingError: nil))

**Comment by JoeMatt** [comment]
@thecb4 What happens if you change your string values to something without colons or backslashes.

I think I ran into something similar with UUID strings that had colons. I believe the decoder is attempting to decode a dictionary before a string, based on the ability to convert "k : v " strings to dictionaries.

If that's a case, a workaround may be to provide your own decoder that specifies the type to try.

I would just try a simple test case first with simple strings to see if that is indeed the issue. I have some example code that might help if that is it.

**Comment by thecb4** [comment]
Now I understand the error message! Perfect.

**Comment by MaxDesiatov** [comment]
hm, I don't think the attempt to decode that string as a dictionary is something anyone expects to be a default behavior. @thecb4 I hope you don't mind if I add that XML snippet to XMLCoder test suite

**Comment by thecb4** [comment]
Thank you. I have been trying to figure out the appropriate work around. I tried a custom init and was still getting the same error. 

```
struct PreviewImageTime: Codable {

  var format: String
  var value: String

  public init(from decoder: Decoder) throws {

      var values = try decoder.container(keyedBy: CodingKeys.self)

      var unkeyedValues = try values.nestedUnkeyedContainer(forKey: .value) as UnkeyedDecodingContainer

      format = try values.decode(String.self, forKey: .format)
      value = try unkeyedValues.decode(String.self, forKey: .value)

  }

  enum CodingKeys: String, CodingKey {
    case format
    case value = ""
  }

  static func nodeEncoding(forKey key: CodingKey) -> XMLEncoder.NodeEncoding {
    print("node encoding")
    switch key {
      case CodingKeys.format:
        return .attribute
      default:
        return .element
    }
  }
}
```

**Comment by thecb4** [comment]
FYI - When I create a standalone XML element, it works. When it's embedded in another element. it fails.


```
// This passes
  let previewTime = 
  """
  <?xml version="1.0" encoding="UTF-8"?>
  <preview_image_time format="24/999 1000/nonDrop">00:00:17:01</preview_image_time>
  """.data(using: .utf8)!


  let decoder = XMLDecoder()
  decoder.errorContextLength = 10

  let metadata1 = try decoder.decode(PreviewImageTime.self, from: previewTime)
  print(metadata1)

// this does not pass
  let preview = 
  """
  <?xml version="1.0" encoding="UTF-8"?>
  <app_preview display_target="iOS-6.5-in" position="1">
    <preview_image_time format="24/999 1000/nonDrop">00:00:17:01</preview_image_time>
  </app_preview>
  """.data(using: .utf8)!

  let metadata2 = try decoder.decode(AppPreview.self, from: preview)
  print(metadata2)
```

structs 

```
struct AppPreview: Codable {
  var displayTarget: String
  var position: Int
  var previewImageTime: PreviewImageTime
  // var dataFile: DataFile

  enum CodingKeys: String, CodingKey {
    case displayTarget = "display_target"
    case position
    case previewImageTime = "preview_image_time"
    // case dataFile = "data_file"
  }
}

struct PreviewImageTime: Codable, DynamicNodeEncoding {

  var format: String
  var value: String

  enum CodingKeys: String, CodingKey {
    case format
    case value
  }

  static func nodeEncoding(forKey key: CodingKey) -> XMLEncoder.NodeEncoding {
    print("node encoding")
    switch key {
      case CodingKeys.format:
        return .attribute
      default:
        return .element
    }
  }
}
```

**Comment by MaxDesiatov** [comment]
Thank you @thecb4, that's very helpful! Clearly looks like a bug to me, looking into it right now.
