### ISSUE TITLE
[Swift 5.1] Import FoundationXML rather than Foundation

### ISSUE THREAD

**Issue by jsbean** [MaxDesiatov/XMLCoder#121]
As of [this PR](https://github.com/apple/swift-corelibs-foundation/pull/2432) onto the Swift 5.1 branch, `XMLParser` lives in a split-off `FoundationXML` framework rather than `Foundation`.

Once Swift 5.1 drops, perhaps we check against the compiler version to import accordingly?

This is a reality as of [DEVELOPMENT-SNAPSHOT-2019-08-03-a](https://github.com/apple/swift/releases).

**Comment by MaxDesiatov** [comment]
As far as I understand, the recommended way is to use `canImport` like this:

```swift
#if canImport(FoundationXML)
import FoundationXML
#endif
```

Probably can even be included before 5.1 release.

**Comment by mxcl** [comment]
5.1 was released. Can submit PR. Need it for production use of this library.

**Comment by MaxDesiatov** [comment]
@mxcl very excited to see this library in production! Please let me know if that's public, I'd be happy to feature it in the README file.

5.1 support is in `master` now and I plan to tag a new release with that ASAP.

**Comment by mxcl** [comment]
Use is private currently, will advise when we're more public! Thanks for the lib, was essential for our backend services.

**Comment by jsbean** [comment]
@MaxDesiatov, looks like you took care of this in #133! Want me to close this down, or is there anything else that needs to be done?

**Comment by MaxDesiatov** [comment]
@jsbean, thanks for checking! I'll keep this open until 0.9 is formally released, primarily as a reminder for this to be added to the CHANGELOG file etc.

**Comment by MaxDesiatov** [comment]
Closing as fixed in the imminent 0.9 release.
