### ISSUE TITLE
Root level attributes don't get encoded back to attribute when converting back to XML file from Plist

### ISSUE THREAD

**Issue by MehmetBal** [MaxDesiatov/XMLCoder#127]
Hi,

First of all thanks for creating such a useful library!  I am having a bit of a hard time with root-level attribute encoding. 

I have a complex XML that requires a big model but to simply:

To decode something this:

```
<?xml version="1.0" encoding="UTF-8"?>
<policy name = "..." attr2="...">
   <Initial>
    more xml here
     .....
     ....
  </Initial>
</policy>
```
I am doing 

```
struct Policy: Codable, Equatable, DynamicNodeEncoding {
    var name: String
    var initial: Initial
enum CodingKeys: String, CodingKey {
        case name,  initial
    }

static func nodeEncoding(for key: CodingKey) -> XMLEncoder.NodeEncoding {
        switch key {
        case CodingKeys.name
            return .attribute
        default:
            return .element
        }
    }
}
```
Then I decode using XMLDecoder(), encode to PLIST using PropertyListEncoder() then encode back to XML with first PropertyListDecoder() and then 
```
            let data = try encoder.encode(modifiedData, withRootKey: "policy",
                                          header: XMLHeader(version: 1.0,
                                                            encoding: "UTF-8"))
```
and everything works gets encoded properly except the root level attributes. 
The result becomes:
```
<policy><name>generic</name>
<initial>
   .....
   .....
</initial>
</policy>
```
I tried `.both` instead of just encoding as `.attribute` but that did not make a difference.

Any ideas on how to fix this?

Thanks

**Comment by MaxDesiatov** [comment]
Hi @MehmetBal, can you please have a look at #134? We aren't able to reproduce the issue with the test added in that PR. Please feel free to reopen this issue if anything's missing.

**Comment by MaxDesiatov** [comment]
This issue hasn't been updated for more than a few months, I'm assuming it can be closed as outdated.
