### ISSUE TITLE
Float vs Float64=Double not parsing 3.14

### ISSUE THREAD

**Issue by marcblanchet** [MaxDesiatov/XMLCoder#130]
if string = "3.14" (which is a valid Float literal), and Codable class contains var myFloat: Float?, on MacOSX 10.14, it does not parse. If I change "typealias Unboxed = Float64"  (Float64 seems to be Double from Apple) to Float like: "typealias Unboxed = Float" in FloatBox.swift , then parsing works.

**Comment by MaxDesiatov** [comment]
Hi @marcblanchet, thanks for reporting this, this is fixed in #138.
