### ISSUE TITLE
Bundle identifier in wrong format

### ISSUE THREAD

**Issue by JanVrabel** [MaxDesiatov/XMLCoder#164]
Hi, impressive work (also on CoreXLSX). Just small idea: (maybe I am wrong but) I think if the bundle identifier wont be in com.company.XMLCoder format it can cause problems with signing during the installation on device or upload to appstore.
Thnx a lot for frameworks like this 👍

**Comment by MaxDesiatov** [comment]
Hey @JanVrabel, this is fixed in #165 and will be released in the next 0.10 version. Thank you so much for your feedback, this is really inspiring 🙂
