### ISSUE TITLE
(Help using) How to decode this XML?

### ISSUE THREAD

**Issue by thefredelement** [MaxDesiatov/XMLCoder#180]
Hi, 

This is an awesome framework, thank you for making it. I have an XML that looks like this:

```
<Response>
  <status>success</status>
  <Things>
    <Thing>
      <ID>123456</ID>
    </Thing>
  </Things>
</Response>

```

And a Codable that looks like this:
```
struct ResponseThing: Codable {
  let ID: String
}

struct Response: Codable {

  let status: String
  let Things: [ResponseThing]
}

```

throws a missing key error... what am I missing?

**Comment by thomasnordquist** [comment]
`let Things: [ResponseThing]` would decode an array of `Things` not an array of `Thing`

To decode the given XML you would need something like

```swift
struct Response: Codable {
  let status: String
  let Things: ThingContainer
}

struct ThingContainer: Codable {
  let Thing: [ResponseThing]
}

struct ResponseThing: Codable {
  let ID: String
}
```

**Comment by thefredelement** [comment]
As soon as I read that I got it, thank you!!!
