### ISSUE TITLE
Use 2 spaces instead of 4 when .prettyPrinted

### ISSUE THREAD

**Issue by owenzhao** [MaxDesiatov/XMLCoder#183]
As Xcode exported .xliff files uses two spaces, I just want them to be aligned.

The left is decoded and then encoded by XMLCoder, the right is Xcode exported original.
<img width="1602" alt="xliffs" src="https://user-images.githubusercontent.com/2182896/82798235-d4339280-9eaa-11ea-9a49-ff76e0387e2d.png">

**Comment by MaxDesiatov** [comment]
Thanks for reporting this @owenzhao, I'll have a look.

**Comment by MaxDesiatov** [comment]
@owenzhao you'll need to set the `prettyPrintIndentation` property on your encoder to `.spaces(2)`. This feature is now available in `master`.
