### ISSUE TITLE
&#10; in XML attributes

### ISSUE THREAD

**Issue by owenzhao** [MaxDesiatov/XMLCoder#185]
In xliff exported by Xcode, \&#10; is a replacement for \n. However, when decoded and encoded by XMLCoder, the \&#10; is replaced by a hard line break

original by Xcode

    <trans-unit id="Got an attributed String.&#10;Will create a image.&#10;&#10;" xml:space="preserve">

decoded and encoded by XMLEncoder

    <trans-unit id="Got an attributed String.
    Will create a image.
    
    " xml:space="preserve">

However, the latter is then not accepted by Xcode as a valid translation.

## My Question
Should I think this as a bug of XMLCoder or something that I should deal with in my own app?

**Comment by MaxDesiatov** [comment]
Hi @owenzhao, thanks for reporting this. With the new API in `master` you can do something like `encoder.charactersEscapedInAttributes += [("\n", "&#10;")]` to make it work for your case.
