### ISSUE TITLE
" in XML element may not always be escaping

### ISSUE THREAD

**Issue by owenzhao** [MaxDesiatov/XMLCoder#187]
In xliff exported by Xcode, most of the time there is a note element, like this 

    <note>Class = "NSTextFieldCell"; title = "Table View Cell"; ObjectID = "2Mq-0d-Xix";</note>

When decoded and encoded by XMLCoder, the "s in the  element's value are escaping.

    <note>Class = &quot;NSTextFieldCell&quot;; title = &quot;Table View Cell&quot;; ObjectID = &quot;2Mq-0d-Xix&quot;;</note>

Both are accepted by Xcode. Just the latter is not as clear as the prior in raw format for human reading.

**Comment by MaxDesiatov** [comment]
With the new API in `master` you can do something like this:

```swift
let encoder = XMLEncoder()
encoder.charactersEscapedInElements = [
        ("&", "&amp;"),
        ("<", "&lt;"),
        (">", "&gt;"),
        ("'", "&apos;"),
    ]
```

This will disable the `&quot;` substitution, but preserve the rest of the default ones.
