### ISSUE TITLE
DynamicNodeEncoding doesn't work on root element

### ISSUE THREAD

**Issue by JamesVanBoxtel** [MaxDesiatov/XMLCoder#194]
Thanks for the amazing open source project.

While using it I noticed that implementing `DynamicNodeEncoding` in order to encode a property as an attribute works great for sub elements, but always encodes as an element for the root element.

```swift
struct SplitsData: Codable, DynamicNodeEncoding {
    var version: String

    enum CodingKeys: String, CodingKey {
        case version = "version"
    }
    
    static func nodeEncoding(for key: CodingKey) -> XMLEncoder.NodeEncoding {
        switch key {
        case CodingKeys.version:
            return .attribute
        default:
            return .both
        }
    }
}

let encoder = XMLEncoder()
let encodedRun = try encoder.encode(self.run, withRootKey: "Run", header: XMLHeader(version: 1.0,
    encoding: "UTF-8"))
try encodedRun.write(to: url)
```

output is something like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Run>
	<version>1.8.0</version>
</Run>
```

**Comment by MaxDesiatov** [comment]
Thanks for creating the issue, I'll have a look.

**Comment by MaxDesiatov** [comment]
@JamesVanBoxtel are you sure you're using the latest version of XMLCoder? I've tried to reproduce the issue [in a test](https://github.com/MaxDesiatov/XMLCoder/pull/195/files), but the `version` attribute is correctly encoded as an attribute. Could you have a look at that test to verify that I'm not missing anything? Maybe there's something else in your code that could have an impact?

**Comment by MaxDesiatov** [comment]
With no updates from the OP and no similar reports I'm closing this as stale
