### ISSUE TITLE
Fail to build in Xcode 12 beta

### ISSUE THREAD

**Issue by tantakan** [MaxDesiatov/XMLCoder#196]
The following error occurs on the Carthage build:
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in XMLDecoder.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

environment:
Xcode Version: 12 beta 3
Carthage: 0.35.0

related issue:
Undefined symbol: type metadata for Swift._StringObject.Variant
https://developer.apple.com/forums/thread/649918

**Comment by MaxDesiatov** [comment]
Thank you for reporting this. Unfortunately, it seems like an Xcode bug, so I'm not sure what can be done about that at the moment. If it persists in GM or maybe even later betas we'll need to start looking for some workaround. PRs are very welcome, as usual 🙂

**Comment by tantakan** [comment]
Thank you for your reply, but it looks fixed in Xcode 12 beta4 (String issue) 👀
