### ISSUE TITLE
nodeEncodingStrategy

### ISSUE THREAD

**Issue by khoogheem** [MaxDesiatov/XMLCoder#49]
Would like to see if it would be possible to look at extending the definition of the custom node encoding strategy.  Or create another custom type

```
        case custom((Encodable.Type, Encoder) -> ((CodingKey) -> XMLEncoder.NodeEncoding))
```

What would be nice is if we can provide the Value.

```
        case custom((Encodable.Type, Encoder) -> ((Value) -> XMLEncoder.NodeEncoding))
```

here is the use case.  Given a node type may have attributes using different keys names, I have created a AttributeBox.

```
public struct Attribute<Value> {

    public let value: Value

    public init(_ value: Value) {
        self.value = value
    }
}

extension Attribute: Encodable where Value: Encodable {
    public func encode(to encoder: Encoder) throws {
        try self.value.encode(to: encoder)
    }
}

extension Attribute: Decodable where Value: Decodable {
    public init(from decoder: Decoder) throws {
        self.init(try Value(from: decoder))
    }
}
```

So it would be nice to be able to say for Node `Activity` use the Type `Attribute<Any>` as the attribute

**Comment by khoogheem** [comment]
looks like pull #73 covers this

**Comment by MaxDesiatov** [comment]
@khoogheem Sorry for being late, as #73 was merged, did that resolve your issue?

**Comment by khoogheem** [comment]
Yep that looks like it should..
