### ISSUE TITLE
OutputFormatting = .sortedKeys

### ISSUE THREAD

**Issue by VadimPavlov** [MaxDesiatov/XMLCoder#52]
I believe there is no reason for @available in (legacy code from JSONEncoder?)
`@available(macOS 10.13, iOS 11.0, watchOS 4.0, tvOS 11.0, *)`
`public static let sortedKeys = OutputFormatting(rawValue: 1 << 1)`

**Comment by regexident** [comment]
You're absolutely right, @VadimPavlov!

I created a PR for it: https://github.com/MaxDesiatov/XMLCoder/pull/53

**Comment by MaxDesiatov** [comment]
Thanks for the report @VadimPavlov, #53 has been merged to `master` now and I believe this issue can be closed. Please feel free to reopen it with more details if needed.
