### ISSUE TITLE
Empty elements fail to decode to optionals in 0.3.0

### ISSUE THREAD

**Issue by stonedauwg** [MaxDesiatov/XMLCoder#68]
After upgrading to 0.3.0, XML elements that are empty and mapped to an optional String fail to decode. Rolling back to 0.2.1 works.

Example struct:

```
struct BarcodeData : Decodable {
    var type = 0
    var barcodeType: String?
    var length = 0
    var barcode = ""
    
    private enum CodingKeys: String, CodingKey {
        case type = "Type"
        case barcodeType = "BarcodeType"
        case length = "Length"
        case barcode = "Barcode"
    }
    
    init() {}
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.type = try container.decode(Int.self, forKey: .type)
        if container.contains(.barcodeType) {
            self.barcodeType = try container.decode(String.self, forKey: .barcodeType)
        }
        self.length = try container.decode(Int.self, forKey: .length)
        self.barcode = try container.decode(String.self, forKey: .barcode)
    }
}
```

Example data:
`<BarcodeData><Type>67</Type><BarcodeType></BarcodeType><Length>4</Length><Barcode>1112</Barcode></BarcodeData>`

In version 0.3.0 decoding results in this error:
Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "BarcodeType", intValue: nil)], debugDescription: "Expected String value but found null instead.", underlyingError: nil))

In 0.2.1 decoding simply leaves the optional String nil like expected

**Comment by MaxDesiatov** [comment]
Many thanks for reporting this @stonedauwg. I'm not even sure it should have worked in 0.2.1 as it was written. What happens here is that you check for presence of a key in the xml (`<BarcodeType></BarcodeType>`), which is present, and then try to decode `String` (not `String?`) from its contents, which is missing.

You probably wanted something like `try container.decode(String?.self, forKey: . barcodeType)` or `try container.decodeIfPresent(String.self, forKey: .barcodeType)` instead. I've covered both of these cases in #69 and those work without a problem in 0.3.0.

What explains this change is that I fixed optional handling for other cases in 0.3.0, which were totally broken (covered in [`UnkeyedTests`](https://github.com/MaxDesiatov/XMLCoder/blob/master/Tests/XMLCoderTests/Minimal/UnkeyedTests.swift) in 0.3.0):

```
struct NilContainer: Codable, Equatable {
  let value: [String]?
}

struct NestedNilContainer: Codable, Equatable {
  let value: [String?]
}

struct NilOfNilsContainer: Codable, Equatable {
  let value: [String?]?
}
```

So most probably that fix made `container.contains` return `true` for empty elements, not `false` like earlier, which I think is expected. Absence of an element and an empty element are different things and you might want to handle those differently.

Please let me know if this makes sense. Hope your code can be updated to reflect these changes and this could be resolved.

**Comment by stonedauwg** [comment]
Interesting. Didn't know about decodeIfPresent or that you could pass an optional type to decode. Will try and let you know

**Comment by stonedauwg** [comment]
Indeed as you stated both techniques work in this case. Thanks @MaxDesiatov !
