### ISSUE TITLE
plist missing CFBundleVersion - fails AppStore Connect upload

### ISSUE THREAD

**Issue by stonedauwg** [MaxDesiatov/XMLCoder#72]
Using carthage to either grab the latest prebuilt binary 0.3.0 or forcing carthage to build the latest XmlCoder results in the framework's plist missing a value for CFBundleVersion, which is required for AppStore Connect upload. Other plist keys are correctly filled in. I see it's using the $(CURRENT_PROJECT_VERSION) variable for CFBundleVersion. Perhaps that is not resolving when built with carthage? Also - looking at the project.pbxproj file - I do not see a project version at all

AppStore error: ERROR ITMS-90056: XMLCoder.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion

**Comment by MaxDesiatov** [comment]
Thanks @stonedauwg! I've bumped the version and set it in the project file. Will tag and release it ASAP

**Comment by MaxDesiatov** [comment]
This has been released as 0.3.1 and pushed to CocoaPods as well. Please reopen this if you still see any issues.
