### ISSUE TITLE
Crash: Range invalid bounds in XMLStackParser.swift

### ISSUE THREAD

**Issue by JoeMatt** [MaxDesiatov/XMLCoder#83]
Line 59,

If `xmlParser.lineNumber` is 0 this will throw
```swift
 for i in 0..<xmlParser.lineNumber - 1 {
            errorPosition += lines[i].count
        }
```

Fix locally with

```swift
        let rangeMax = max(xmlParser.lineNumber - 1, 0)
        for i in 0..<rangeMax {
```

Not sure if this logic if correct though, instead of throwing or skipping the for loop.

**Comment by MaxDesiatov** [comment]
Thank you for reporting this @JoeMatt. This is fixed in #84.
